name: samvaad
description: A new Flutter project.
version: 1.0.0+1
versionName: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.0
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  shimmer: ^3.0.0
  new_gradient_app_bar: ^0.2.0
  image_picker: ^1.0.2
  path_provider: ^2.0.0
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  cached_network_image: ^3.0.0-nullsafety.0
  agora_rtc_engine: ^6.2.2
  permission_handler: ^10.4.3
  hive: ^2.2.3
  sqflite: ^2.0.0
  file_picker: ^5.3.2
  flutter_downloader: ^1.6.1
  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - app_logo.png
    - assets/logo.png
    - assets/user.png
    - assets/picture.png
    - assets/sale.png
    - assets/mii.jpeg
    - assets/bg_chat.png
    - assets/bg.png
